---
title: "Pump Data"
format: html
---

```{r Packages, warning=FALSE, message=FALSE}
library(here)
library(tidyverse)
library(LMMstar)
library(readr)
library(rstatix)
library(kableExtra)
library(fs)
library(lubridate)
source(here("R/functions.R"))
```

```{r Stenopool import, warning=FALSE, message=FALSE}
stenopool_basal_base <- read.csv(here("data-raw/pump_base/stenopool/73_prepare_2_weeks_arm_1_cgmupload_pump_3.csv")) |> 
  select(
    start,
    end,
    units,
    deliveryMode
  ) |> 
  rename(
    type = deliveryMode
  ) |> 
  mutate(
    id = "73",
    platform = "Stenopool",
    start = as.POSIXct(start, format = "%Y-%m-%dT%H:%M"),
    end = as.POSIXct(end, format = "%Y-%m-%dT%H:%M"),
    duration_min = as.numeric(difftime(end, start, units = "mins")),
    num_intervals = ceiling(duration_min / 5),
    units_new = units/60*duration_min
  ) |> 
  filter(!is.na(num_intervals)) |> 
  uncount(num_intervals, .id = "interval_id") %>%
  mutate(
    timestamp = start + minutes(5 * (interval_id - 1)),
    units_5min = (units_new / duration_min) * 5
  ) |> 
  select(
    id,
    platform,
    timestamp,
    type, 
    units_5min
    ) |> 
  rename(
    datetime = timestamp,
    units = units_5min
  )

stenopool_bolus_base <- read.csv(here("data-raw/pump_base/stenopool/73_prepare_2_weeks_arm_1_cgmupload_pump_2.csv")) |> 
  mutate(
    id = "73",
    platform = "Stenopool",
    type = "bolus",
    datetime = as.POSIXct(time, format = "%Y-%m-%dT%H:%M")
  )|> 
  select(
    id,
    platform,
    datetime,
    type,
    units
  ) 

stenopool_insulin <- stenopool_basal_base |> 
  full_join(stenopool_bolus_base) |> 
  mutate(
    date = date(datetime),
    hour = hour(datetime),
    min = minute(datetime),
    days = as.numeric(max(datetime)-min(datetime)+1)
  ) |> 
  select(
    id,
    platform,
    date,
    datetime,
    hour,
    min,
    type,
    units,
    days
  )
```

```{r Stenopool averages}
basal_minmax <- stenopool_insulin |> 
  group_by(
    id
  ) |>
  filter(
    type != "bolus"
  ) |> 
  mutate(
    days = as.numeric(max(datetime)-min(datetime)),
    sum_insulin = sum(units),
    basal_average = sum_insulin/days
  ) |> 
  summarise(
    basal_average = mean(basal_average),
    days = mean(days)
  )

bolus_minmax <- stenopool_insulin |> 
  group_by(
    id
  ) |>
  filter(
    type == "bolus"
  ) |> 
  mutate(
    days = as.numeric(max(datetime)-min(datetime)),
    sum_insulin = sum(units),
    bolus_average = sum_insulin/days
  ) |> 
  summarise(
    bolus_average = mean(bolus_average),
    days = mean(days)
  )

units_average <- basal_minmax |> 
  full_join(bolus_minmax) |> 
  mutate(
    units_average = basal_average+bolus_average
  ) |> 
  select(
    id,
    basal_average,
    bolus_average,
    units_average,
    days
  )
```

```{r Carelink}
carelink_basal_base_duration <- read.csv2(here("data-raw/pump_base/carelink/4_prepare_2_weeks_arm_1_cgmupload_pump_2.csv"), nrows = 1) |> 
  mutate(
    id = "4",
    platform = "Carelink",
    Start.Date =  as.POSIXct(Start.Date, format = "%d-%m-%Y"),
    End.Date = as.POSIXct(End.Date, format = "%d-%m-%Y")
  ) |> 
  select(
    id,
    platform,
    Start.Date,
    End.Date
  )

carelink_basal_base <- read.csv2(here("data-raw/pump_base/carelink/4_prepare_2_weeks_arm_1_cgmupload_pump_2.csv"), skip = 6) |> 
  select(
    Date,
    Time,
    Basal.Rate..U.h.
  ) |> 
  rename(
    date = Date,
    time = Time,
    units = Basal.Rate..U.h.
  ) |> 
  mutate(
    id = "4",
    platform = "Carelink",
    date = as.POSIXct(date, format = "%Y/%m/%d"),
    units = str_replace_all(units, ",", "."),
    units = as.numeric(units),
    type = "Scheduled",
    datetime = paste(date, time, sep = " "),
    datetime = as.POSIXct(datetime, format = "%Y-%m-%d %H:%M:%S"),
    hour = hour(datetime),
    min = minute(datetime)
  ) |> 
  filter(
    !is.na(units)
  ) |> 
  distinct() |> 
  full_join(carelink_basal_base_duration) |> 
  mutate(
    start_check = as.numeric(date-Start.Date),
    end_check = as.numeric(End.Date-date)
  )  |>
  filter(
    start_check >= "0",
    end_check >= "0"
  ) |> 
  mutate(
    datetime_end = datetime,
    datetime_start = lead(datetime)
  ) |> 
  mutate(
    duration_min = as.numeric(difftime(datetime_end, datetime_start, units = "mins")),
    num_intervals = ceiling(duration_min / 5),
    units_new = units/60*duration_min
  ) |> 
  filter(!is.na(num_intervals)) |> 
  uncount(num_intervals, .id = "interval_id") %>%
  mutate(
    timestamp = datetime_start + minutes(5 * (interval_id - 1)),
    units_5min = (units_new / duration_min) * 5
  ) |> 
  select(
    id,
    platform,
    timestamp,
    type, 
    units_5min
    ) |> 
  rename(
    datetime = timestamp,
    units = units_5min
  )


```

